repo_url: https://github.com/SBD1/2025.01-Estagio-de-TI
repo_name: 2025.01-Estagio-de-TI
site_url: https://github.com/SBD1/2025.01-Estagio-de-TI

site_name: Estagiario de TI
nav:
  - Inicio: "index.md"
  - Apresentação:
    - Apresentaçôes: "apresentacao/apresentacao.md"
  - Entrega 1:
    - Diagrama Entidade Relacionamento: "modulo1/der.md"
    - Modelo Entidade Relacionamento: "modulo1/mer.md"
    - Dicionário de Dados: "modulo1/dd.md"
    - Modelo Relacional: "modulo1/mr.md"
  - Entrega 2:
  #  - Normalização: ""
    - Data Definition Language: "modulo2/ddl.md"
    - Data Manipulation Language: "modulo2/dml.md"
    - Data Query Language: "modulo2/dql.md"
  #  - Algebra Relacional: ""
    - Terminal: "modulo2/terminal.md"

theme:
  name: material
  logo: assets/imagens/logo.png
  favicon: assets/imagens/logo.png
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: green

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: green
